#!/bin/bash
time=$(date +%M)
if [ "$time" -lt 20 ] ; then
        sleep 1
elif [ "$time" -gt 19 ] ; then
        echo -e "\a"
else [ "$time" -gt 39 ]
        echo -e "\a"
        sleep 1
        echo -e "\a"
fi
